// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDj8qPpypcPTh99ogHMM61Inxjq7cjwfdE',
    appId: '1:710526714487:web:a933ac6d0ed6ad71f4fc72',
    messagingSenderId: '710526714487',
    projectId: 'voice-todo-91c86',
    authDomain: 'voice-todo-91c86.firebaseapp.com',
    databaseURL: 'https://voice-todo-91c86-default-rtdb.firebaseio.com',
    storageBucket: 'voice-todo-91c86.firebasestorage.app',
    measurementId: 'G-H6J4MP76EX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1f5hRegToni5gx9Y2HQ8jTr-GTiylo-4',
    appId: '1:710526714487:android:cd3976ecc994987cf4fc72',
    messagingSenderId: '710526714487',
    projectId: 'voice-todo-91c86',
    databaseURL: 'https://voice-todo-91c86-default-rtdb.firebaseio.com',
    storageBucket: 'voice-todo-91c86.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADl_d8VcordTUuPfB1NWorVSCSWpIg3_M',
    appId: '1:710526714487:ios:7f7d61e10d398a16f4fc72',
    messagingSenderId: '710526714487',
    projectId: 'voice-todo-91c86',
    databaseURL: 'https://voice-todo-91c86-default-rtdb.firebaseio.com',
    storageBucket: 'voice-todo-91c86.firebasestorage.app',
    iosBundleId: 'com.example.voiceTodo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADl_d8VcordTUuPfB1NWorVSCSWpIg3_M',
    appId: '1:710526714487:ios:7f7d61e10d398a16f4fc72',
    messagingSenderId: '710526714487',
    projectId: 'voice-todo-91c86',
    databaseURL: 'https://voice-todo-91c86-default-rtdb.firebaseio.com',
    storageBucket: 'voice-todo-91c86.firebasestorage.app',
    iosBundleId: 'com.example.voiceTodo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDj8qPpypcPTh99ogHMM61Inxjq7cjwfdE',
    appId: '1:710526714487:web:d9fb9bf53aa173dff4fc72',
    messagingSenderId: '710526714487',
    projectId: 'voice-todo-91c86',
    authDomain: 'voice-todo-91c86.firebaseapp.com',
    databaseURL: 'https://voice-todo-91c86-default-rtdb.firebaseio.com',
    storageBucket: 'voice-todo-91c86.firebasestorage.app',
    measurementId: 'G-3XZRZ2NGR0',
  );
}
